# Created by Kelvin_Clark on 1/30/2022, 11:59 PM
MODE_KEY = "MODE"
DEV_MODE = "DEVELOPMENT"
PROD_MODE = "PRODUCTION"
DEV_SYNC_DATABASE_KEY = "DEV_DATABASE_URL_SYNC"
DEV_ASYNC_DATABASE_KEY = "DEV_DATABASE_URL_ASYNC"
PROD_SYNC_DATABASE_KEY = "PROD_DATABASE_URL_SYNC"
PROD_ASYNC_DATABASE_KEY = "PROD_DATABASE_URL_ASYNC"

