# Created by Kelvin_Clark on 1/30/2022, 11:59 PM
SYNC_DATABASE_URL_KEY = "SYNC_DATABASE_URL"
ASYNC_DATABASE_URL_KEY = "ASYNC_DATABASE_URL"
SECRET_KEY_ENV_KEY = "SECRET_KEY"
MODE_ENV_KEY = "MODE"
DEVELOPMENT_MODE = "development"
PRODUCTION_MODE = "production"
TEST_BASE_URL = "http://test"
TEST_GRAPHQL_PATH = "/test_graphql"
ROWS_PER_PAGE = 20
DB_SESSION_SYNC = "db_session_sync"
DB_SESSION_ASYNC = "db_session_async"
COMMENT_ADDED_EVENT = "comment_added_event"
