# Created by Kelvin_Clark on 1/30/2022, 11:59 PM
SYNC_DATABASE_URL_KEY = "SYNC_DATABASE_URL"
ASYNC_DATABASE_URL_KEY = "ASYNC_DATABASE_URL"
SECRET_KEY_ENV_KEY = "SECRET_KEY"
MODE_ENV_KEY = "MODE"
DEVELOPMENT_MODE = "development"
PRODUCTION_MODE = "production"
