"""Add date_created field to ticket

Revision ID: 5ab29d80ef60
Revises: 0b9400bc32c5
Create Date: 2022-02-03 12:33:47.049288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab29d80ef60'
down_revision = '0b9400bc32c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'date_created')
    # ### end Alembic commands ###
